[server]
port = 1003



[node]
[[node.driver-configuration]]
display-name = "firefox"
stereotype = "{\"browserName\": \"firefox\", \"platformName\": \"Linux\" }"

[[node.driver-configuration]]
display-name = "chrome"
stereotype = "{\"browserName\": \"chrome\",  \"platformName\": \"Linux\"}"


[[node.driver-configuration]]
display-name = "internet explorer"
stereotype = "{\"browserName\": \"internet explorer\", \"platformName\": \"Linux\"}"


[[node.driver-configuration]]
display-name = "MicrosoftEdge"
stereotype = "{\"browserName\": \"MicrosoftEdge\", \"platformName\": \"Linux\"}"


[[node.driver-configuration]]
display-name = "safari"
stereotype = "{\"browserName\": \"safari\", \"platformName\": \"Linux\"}"





