[server]
port = 1001



[node]
[[node.driver-configuration]]
override-max-sessions = true
max-sessions = 2
display-name = "smsm1"
stereotype = "{\"browserName\": \"firefox\", \"browserVersion\": \"93\", \"platformName\": \"MacOs\" }"

[[node.driver-configuration]]
override-max-sessions = true
max-sessions = 2
display-name = "Chrome Beta"
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"94\", \"platformName\": \"Widnows 10\"}"


[[node.driver-configuration]]
override-max-sessions = true
max-sessions = 2
display-name = "Chrome Beta"
stereotype = "{\"browserName\": \"internet explorer\", \"platformName\": \"Widnows 10\"}"


[[node.driver-configuration]]
override-max-sessions = true
max-sessions = 2
display-name = "Chrome Beta"
stereotype = "{\"browserName\": \"MicrosoftEdge\", \"platformName\": \"Widnows 8.1\"}"